export const GET_ADDRESS_REQUEST = 'GetStore/GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GetStore/GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAILURE = 'GetStore/GET_ADDRESS_FAILURE';
